import {
  Icon3ds,
  Iconaac,
  Iconai,
  Iconavi,
  Iconbmp,
  Iconcad,
  Iconcdr,
  Iconcss,
  Icondat,
  Icondll,
  Icondmg,
  Icondoc,
  Iconeps,
  Iconfla,
  Iconflv,
  Icongif,
  Iconhtml,
  Iconindd,
  Iconiso,
  Iconjpg,
  Iconjs,
  Iconmidi,
  Iconmov,
  Iconmp3,
  Iconmpg,
  Iconpdf,
  Iconphp,
  Iconpng,
  Iconppt,
  Iconps,
  Iconpsd,
  Iconraw,
  Iconsql,
  Iconsvg,
  Icontif,
  Icontxt,
  Iconwmv,
  Iconxls,
  Iconxml,
  Iconzip,
} from "./SVGs";

import { Iconkey, Iconnumbers, Iconpages, Iconr3d } from "./PNGs";

const fileIcons = {
  "3ds": `<img src=${Icon3ds} alt="3ds file" />`,
  aac: `<img src=${Iconaac} alt="aac file" />`,
  ai: `<img src=${Iconai} alt="ai file" />`,
  avi: `<img src=${Iconavi} alt="avi file" />`,
  bmp: `<img src=${Iconbmp} alt="bmp file" />`,
  cad: `<img src=${Iconcad} alt="cad file" />`,
  cdr: `<img src=${Iconcdr} alt="cdr file" />`,
  css: `<img src=${Iconcss} alt="css file" />`,
  dat: `<img src=${Icondat} alt="dat file" />`,
  dll: `<img src=${Icondll} alt="dll file" />`,
  dmg: `<img src=${Icondmg} alt="dmg file" />`,
  doc: `<img src=${Icondoc} alt="doc file" />`,
  eps: `<img src=${Iconeps} alt="eps file" />`,
  fla: `<img src=${Iconfla} alt="fla file" />`,
  flv: `<img src=${Iconflv} alt="flv file" />`,
  gif: `<img src=${Icongif} alt="gif file" />`,
  html: `<img src=${Iconhtml} alt="html file" />`,
  indd: `<img src=${Iconindd} alt="indd file" />`,
  iso: `<img src=${Iconiso} alt="iso file" />`,
  jpg: `<img src=${Iconjpg} alt="jpg file" />`,
  js: `<img src=${Iconjs} alt="js file" />`,
  key: `<img src=${Iconkey} alt="key file" />`,
  // keynote: `<img src=${Iconkeynote} alt="keynote file" />`,
  midi: `<img src=${Iconmidi} alt="midi file" />`,
  mov: `<img src=${Iconmov} alt="mov file" />`,
  mp3: `<img src=${Iconmp3} alt="mp3 file" />`,
  mpg: `<img src=${Iconmpg} alt="mpg file" />`,
  numbers: `<img src=${Iconnumbers} alt="numbers file" />`,
  pages: `<img src=${Iconpages} alt="pages file" />`,
  pdf: `<img src=${Iconpdf} alt="pdf file" />`,
  php: `<img src=${Iconphp} alt="php file" />`,
  png: `<img src=${Iconpng} alt="png file" />`,
  ppt: `<img src=${Iconppt} alt="ppt file" />`,
  ps: `<img src=${Iconps} alt="ps file" />`,
  psd: `<img src=${Iconpsd} alt=psd file" />`,
  r3d: `<img src=${Iconr3d} alt="r3d file" />`,
  raw: `<img src=${Iconraw} alt="raw file" />`,
  sql: `<img src=${Iconsql} alt="sql file" />`,
  svg: `<img src=${Iconsvg} alt="svg file" />`,
  tif: `<img src=${Icontif} alt="tif file" />`,
  txt: `<img src=${Icontxt} alt="txt file" />`,
  wmv: `<img src=${Iconwmv} alt="wmv file" />`,
  xls: `<img src=${Iconxls} alt="xls file" />`,
  xml: `<img src=${Iconxml} alt="xml file" />`,
  zip: `<img src=${Iconzip} alt="zip file" />`,
};

export default fileIcons;
